INSERT INTO tasks (id, task_title, task_status) VALUES
    (1, 'Go for a morning run', 'DONE'),
    (2, 'Clean the bathroom', 'PENDING'),
    (3, 'Mow the lawn', 'IN_PROGRESS'),
    (4, 'Paint a watercolor', 'DONE'),
    (5, 'Plan a vacation', 'PENDING'),
    (6, 'Take a nap', 'DONE'),
    (7, 'Learn a new language', 'IN_PROGRESS'),
    (8, 'Play guitar for 30 minutes', 'PENDING'),
    (9, 'Water the plants', 'DONE'),
    (10, 'Read a book', 'DONE'),
    (11, 'Take a photography class', 'DONE'),
    (12, 'Visit a museum', 'PENDING'),
    (13, 'Walk the dog', 'DONE'),
    (14, 'Visit a farmers market', 'IN_PROGRESS'),
    (15, 'Paint the fence', 'DONE'),
    (16, 'Attend a sports game', 'DONE'),
    (17, 'Call a friend', 'PENDING'),
    (18, 'Go for a bike ride', 'DONE'),
    (19, 'Go camping this weekend', 'PENDING'),
    (20, 'Plant a vegetable garden', 'IN_PROGRESS'),
    (21, 'Join a fitness class', 'DONE'),
    (22, 'Solve a puzzle', 'DONE'),
    (23, 'Build a birdhouse', 'PENDING'),
    (24, 'Knit a scarf', 'IN_PROGRESS'),
    (25, 'Try a new recipe', 'DONE'),
    (26, 'Explore a new hiking trail', 'DONE'),
    (27, 'Go fishing at the lake', 'PENDING'),
    (28, 'Try a new restaurant downtown', 'DONE'),
    (29, 'Reduce screen time', 'IN_PROGRESS'),
    (30, 'Write a letter to a friend', 'PENDING'),
    (31, 'Meditate for 20 minutes', 'DONE'),
    (32, 'Organize the garage', 'PENDING'),
    (33, 'Declutter the closet', 'IN_PROGRESS'),
    (34, 'Fix the leaky faucet', 'DONE'),
    (35, 'Back up laptop files', 'DONE'),
    (36, 'Cancel unused subscriptions', 'PENDING'),
    (37, 'Schedule a dentist appointment', 'DONE'),
    (38, 'Do a digital detox for a day', 'PENDING'),
    (39, 'Cook a meal from scratch', 'DONE'),
    (40, 'Volunteer at a local shelter', 'IN_PROGRESS'),
    (41, 'Start a journal', 'DONE'),
    (42, 'Learn to bake sourdough bread', 'PENDING'),
    (43, 'Take an online course', 'IN_PROGRESS'),
    (44, 'Set up a budget spreadsheet', 'DONE'),
    (45, 'Deep clean the kitchen', 'PENDING'),
    (46, 'Go stargazing at night', 'DONE'),
    (47, 'Watch a documentary', 'DONE'),
    (48, 'Practice yoga for 30 minutes', 'DONE'),
    (49, 'Repot the houseplants', 'PENDING'),
    (50, 'Plan a monthly budget', 'IN_PROGRESS');